### ISSUE TITLE
Balun transformer

### ISSUE THREAD

**Issue by LightningStalker** [HarrydeBug/CW_Flea#1]
Hello, the output transformer seems to be wired in a step-up or step-down configuration. Can you confirm this? Third party disclosure appears to be unavailable on my end.

**Comment by HarrydeBug** [comment]
The transformer has  an impedance transform ratio of 6.
I made and tried out a few options and the best results was with a BN43-1502 core, primary one turn - secondary 3 turns.

**Comment by LightningStalker** [comment]
Ok thanks.
